---
- name: Create Subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ create_vpc_result.vpc.id }}"
    state: present
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    resource_tags:
      Name: "{{ item.name }}"
  with_items: "{{ create_subnets_subnets }}"
  register: create_subnets_results
